= Lecture 6: Function tables, multiplexers

== Function tables

Function tables are a way to compact down a truth table by removing variable(s) from the input columns and placing it into the output function.
Function tables are so called because the outputs are no longer merely just 0 or 1, but also **any function** of input variables.

=== Example

Here's the truth table for a &oplus; b:

[format="csv", options="header"]
|===
a   , b   , a &oplus; b
0   , 0   , 0
0   , 1   , 1
1   , 0   , 1
1   , 1   , 0
|===

We can condense this down to this function table, by freeing variable b:

[format="csv", options="header"]
|===
a   , a &oplus; b
0   , b
1   , b'
|===

Notice how when a is false, the output function is the same as b.
When a is true, the output function is the inverse of b.

== Multiplexers

Multiplexers (MUX) are circuits that redirect one of several inputs to a single output based on the value of the selector.
That is, the output corresponds to the selected input.

In this respect, multiplexers are equivalent to switch/case statements.

----
boolean Four1MUX(byte selector, boolean input0, boolean input1, boolean input2, boolean input3) {
    switch(selector) {
        case 0: return input0;
        case 1: return input1;
        case 2: return input2;
        case 3: return input3;
    }
    return false;
}
----

The function table for a 4-1 MUX (4 input, 1 output multiplexer) is as follows:

[format="csv", options="header"]
|===
S1,S0,Output
0,0,Input0
0,1,Input1
1,0,Input2
1,1,Input3
|===

Select bits S1 and S0 represent the most and least significant bits of S (respectively) in binary. 

== Truth/function table to multiplexer

To implement a combination logic function with a multiplexer, the number of rows (excluding the header) in the truth/function table must equal the number of inputs to the multiplexer.
If your truth table has more rows than the multiplexer has inputs, write out a function table with the same number of inputs as the multiplexer equivalent to the truth table.

. Align the outputs of your table to the inputs of the multiplexer.
. The select bits will correspond to the input variables.
. Ta-da!
