= CPU Instruction Set Architecture

[format="csv", options="header"]
:===
Component:Hex Machine code:Equivalent Assembly:Equivalent C/C++/Java-esque code:Comments
ALU:`0dab`:ADD Rd, Ra, Rb:`Rd = Ra + Rb;`:ADD Rd, Ra, R0 assigns Ra to Rd, since R0 = 0
ALU:`1dab`:SUB Rd, Ra, Rb:`Rd = Ra - Rb;`:SUB Rd, Ra, R0 assigns Ra to Rd, since R0 = 0
ALU:`2dab`:MUL Rd, Ra, Rb:`Rd = Ra * Rb;`:
ALU:`3dab`:DIV Rd, Ra, Rb:`Rd = Ra / Rb;`:Integer division
ALU:`4dab`:AND Rd, Ra, Rb:`Rd = Ra & Rb;`:Bitwise and
ALU:`5dab`:OR  Rd, Ra, Rb:`Rd = Ra | Rb;`:Bitwise or
ALU:`6dab`:XNOR Rd, Ra, Rb:`Rd = !(Ra ^ Rb);`:Bitwise equality
ALU:`7dmm`:MOV Rd, mm:`Rd = mm;`:Copy constant mm
Program Control:`8dmm`:JZE Ra, mm:`if (Ra == 0) goto mm;`:JZE R0, mm is equivalent to goto mm
Program Control:`9dmm`:JZN Ra, mm:`if (Ra != 0) goto mm;`:
Program Control:`admm`:JZG Ra, mm:`if (Ra > 0) goto mm;`:
Program Control:`bdmm`:JZL Ra, mm:`if (Ra < 0) goto mm;`:
Bus Control:`cdmm`:LOAD Rd, mmm:`Rd = RAM[mmm]; // Rd = *(mmm);`:
Bus Control:`ddxx`:LOAD Rd:`Rd = RAM[Ra]; // Rd = *(Rd);`:
Bus Control:`esmm`:STOR Rs, mm:`RAM[mm] = Rs;`:The store instruction doesn't work at the moment
Bus Control:`fsxx`:STOR Rs:`RAM[Rs & 0xff] = Rs;`:Ditto
:===


Cycle Clock
  0     0    Fetch instruction
  0     1    Fetch instruction
  1     0    Fetch operand / ALU enable
  1     1    Program counter increment, Register write
